version: "3"

services:
  db:
    container_name: database_mysql
    build: ./db
    environment:
      MYSQL_DATABASE: bdwin
      MYSQL_ROOT_PASSWORD: Pesamatic13102006
      MYSQL_USER: bdmaster
      MYSQL_PASSWORD: bdmaster
      DATABASE_HOST: db
  server:
    container_name: win-server
    build: ./server
    environment:
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: bdwin
      MYSQL_USER: bdmaster
      MYSQL_PASSWORD: bdmaster
    ports:
      - "6996:6996"
    depends_on:
      - db
    restart: always
  win:
    container_name: win
    build: ./win
    ports:
      - "3001:3000"
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
